export const personalInfo = {
    fullName: 'Prahlad Yadav',
    firstName: 'Prahlad',
    role: 'Full-Stack Engineer',
    email: 'prahlad.yadav.off@gmail.com',
    location: 'Delhi, India',
    resumeUrl: 'https://drive.google.com/file/d/1WJZfS_LISgbVF3hCU8XHG348yHrlKNjW/view?usp=sharing',
    availability: 'Open to full-time SDE roles',
    intro: 'Backend-first engineer.',
    summary: 'I turn messy problems into clean systems that scale.',
    socialLinks: {
        linkedin: 'https://linkedin.com/in/prahlad-yadav-07',
        github: 'https://github.com/Prahlad-07',
        instagram: 'https://instagram.com/prahlad_07',
    },
};

export const navLinks = [
    { id: 1, name: 'Home', href: '#home' },
    { id: 2, name: 'About', href: '#about' },
    { id: 3, name: 'Experience', href: '#experience' },
    { id: 4, name: 'Skills', href: '#skills' },
    { id: 5, name: 'Projects', href: '#projects' },
    { id: 6, name: 'Recommendations', href: '#recommendations' },
    { id: 7, name: 'Contact', href: '#contact' },
];

export const heroMetrics = [
    { id: 1, value: 'Top 1%', label: 'Competitive Programmer', detail: '3000+ problems solved' },
    { id: 2, value: '5+', label: 'Products Shipped', detail: 'Real users, production code' },
    { id: 3, value: '2500+', label: 'GitHub Commits', detail: '12 months, no gaps' },
    { id: 4, value: '4', label: 'Android Apps', detail: '1000+ campus users' },
];

export const aboutHighlights = [
    { id: 1, title: 'Fast Shipping', text: 'Ideas to working code, quickly. No over-engineering.' },
    { id: 2, title: 'Clean Code', text: 'Readable, documented, easy for anyone to pick up.' },
    { id: 3, title: 'Problem Solver', text: '3000+ problems trained me to think under pressure.' },
];

export const achievements = [
    'AIR 311 — ICPC Kanpur',
    'Rank 1446 / 25,000+ teams — Amazon ML Challenge 2025',
    'LeetCode Guardian 2150+, Codeforces Expert 1680+, CodeChef 4★',
    '5+ full-stack products shipped to real users',
];

export const skillGroups = [
    {
        id: 1,
        title: 'Backend & APIs',
        description: 'My core strength.',
        accent: '#0f766e',
        items: ['Java', 'Spring Boot', 'Spring Security', 'Hibernate', 'REST APIs', 'JWT', 'Microservices', 'Low-Level Design'],
    },
    {
        id: 2,
        title: 'Frontend & UI',
        description: 'React and modern CSS.',
        accent: '#c2410c',
        items: ['React', 'JavaScript', 'Tailwind CSS', 'HTML & CSS', 'Responsive Design', 'Component Design'],
    },
    {
        id: 3,
        title: 'DevOps & Tools',
        description: 'Ship fast, deploy clean.',
        accent: '#1d4ed8',
        items: ['Git & GitHub', 'AWS', 'Docker', 'Maven & Gradle', 'Postman', 'Linux'],
    },
    {
        id: 4,
        title: 'Fundamentals',
        description: 'The deep stuff.',
        accent: '#7c3aed',
        items: ['Data Structures', 'Algorithms', 'Operating Systems', 'Databases (SQL)', 'System Design', 'C/C++'],
    },
];

export const codingProfiles = [
    {
        id: 1,
        platform: 'LeetCode',
        handle: 'Prahlad_07',
        url: 'https://leetcode.com/u/Prahlad_07/',
        highlight: 'Guardian badge, 2150+ max rating.',
        badge: '2150+ Max',
        color: '#d97706',
        icon: '/assets/codingProfiles/Leetcode.png',
    },
    {
        id: 2,
        platform: 'GitHub',
        handle: 'Prahlad-07',
        url: 'https://github.com/Prahlad-07',
        highlight: '2500+ commits in a single year.',
        badge: '2500+ Commits',
        color: '#312e81',
        icon: '/assets/codingProfiles/Github.png',
    },
    {
        id: 3,
        platform: 'Codeforces',
        handle: 'CenterNewHero',
        url: 'https://codeforces.com/profile/CenterNewHero',
        highlight: 'Expert, 1610+ max rating.',
        badge: 'Expert',
        color: '#0369a1',
        icon: '/assets/codingProfiles/codforces.png',
    },
    {
        id: 4,
        platform: 'GeeksforGeeks',
        handle: 'prahlad_07',
        url: 'https://www.geeksforgeeks.org/profile/prahlad_07',
        highlight: '4-star across problem-solving tracks.',
        badge: '4 Star',
        color: '#15803d',
        icon: '/assets/codingProfiles/geekforgeeks.png',
    },
    {
        id: 5,
        platform: 'HackerRank',
        handle: 'Mr_Encrypt',
        url: 'https://www.hackerrank.com/profile/Mr_Encrypt',
        highlight: '6-star in problem solving.',
        badge: '6 Star',
        color: '#16a34a',
        icon: '/assets/codingProfiles/hackerrank.png',
    },
    {
        id: 6,
        platform: 'CodeChef',
        handle: 'mr_shyyy_07',
        url: 'https://www.codechef.com/users/mr_shyyy_07',
        highlight: '4-star, strong contest discipline.',
        badge: '4 Star',
        color: '#ea580c',
        icon: '/assets/codingProfiles/codechef.png',
    },
];

export const myProjects = [
    {
        id: 1,
        title: 'BookMySalon',
        mark: 'BM',
        category: 'Salon booking platform',
        year: '2026',
        repoState: 'Public repo',
        repoUrl: 'https://github.com/Prahlad-07/BookMySalon',
        repoLabel: 'View Repository',
        summary: 'Owners manage bookings; customers discover and book salons nearby.',
        description: 'Full-stack: Java, Spring Boot, React, MySQL.',
        impact: [
            'JWT + Google auth, real-time chat over WebSocket',
            'Time-slot validation with role-based access control',
            'Mapbox discovery, Dockerized backend',
        ],
        availabilityNote: 'Real product, real users, production code.',
        theme: { primary: '#0f766e', secondary: '#d97706' },
        tags: [
            { id: 1, name: 'Java', path: '/assets/file-java-color-green-icon.svg' },
            { id: 2, name: 'Spring Boot', path: '/assets/icons8-spring-boot.svg' },
            { id: 3, name: 'React', path: '/assets/react.svg' },
            { id: 4, name: 'MySQL', path: '/assets/mysql-icon.svg' },
            { id: 5, name: 'Docker' },
            { id: 6, name: 'Mapbox' },
        ],
        images: [
            { id: 1, src: '/assets/Projects-Images/BookMySalon/firstImage.webp', alt: 'BookMySalon landing screen' },
            { id: 2, src: '/assets/Projects-Images/BookMySalon/img.webp', alt: 'BookMySalon booking interface' },
            { id: 3, src: '/assets/Projects-Images/BookMySalon/img_1.webp', alt: 'BookMySalon salon details screen' },
            { id: 4, src: '/assets/Projects-Images/BookMySalon/img_2.webp', alt: 'BookMySalon management flow' },
            { id: 5, src: '/assets/Projects-Images/BookMySalon/secondImage.webp', alt: 'BookMySalon dashboard' },
        ],
    },
    {
        id: 2,
        title: 'GEC-B App',
        mark: 'GA',
        category: 'Campus communication app',
        year: '2025',
        repoState: 'Private repo',
        repoUrl: 'https://github.com/Prahlad-07/GECB_APP',
        repoLabel: 'Repository Link',
        summary: 'Official Android app for my college — notices, timetables, events, one place.',
        description: 'Kotlin, Jetpack Compose, Firebase.',
        impact: [
            'Admin and student dashboards',
            'Firebase auth, messaging, offline support',
            '1000+ students using it daily',
        ],
        availabilityNote: 'Real product, real users, production code.',
        theme: { primary: '#c2410c', secondary: '#0f766e' },
        tags: [
            { id: 1, name: 'Kotlin' },
            { id: 2, name: 'Jetpack Compose' },
            { id: 3, name: 'Firebase' },
            { id: 4, name: 'MVVM' },
            { id: 5, name: 'FCM' },
            { id: 6, name: 'Android' },
        ],
        images: [
            { id: 1, src: '/assets/Projects-Images/GEC-B%20App/1.webp', alt: 'GEC-B App home screen' },
            { id: 2, src: '/assets/Projects-Images/GEC-B%20App/2.webp', alt: 'GEC-B App timetable interface' },
            { id: 3, src: '/assets/Projects-Images/GEC-B%20App/image.webp', alt: 'GEC-B App notice interface' },
            { id: 4, src: '/assets/Projects-Images/GEC-B%20App/image%20copy.webp', alt: 'GEC-B App student dashboard' },
            { id: 5, src: '/assets/Projects-Images/GEC-B%20App/image%20copy%202.webp', alt: 'GEC-B App admin interface' },
            { id: 6, src: '/assets/Projects-Images/GEC-B%20App/image%20copy%203.webp', alt: 'GEC-B App faculty directory' },
            { id: 7, src: '/assets/Projects-Images/GEC-B%20App/image%20copy%204.webp', alt: 'GEC-B App event screen' },
            { id: 8, src: '/assets/Projects-Images/GEC-B%20App/image%20copy%205.webp', alt: 'GEC-B App community screen' },
            { id: 9, src: '/assets/Projects-Images/GEC-B%20App/image%20copy%206.webp', alt: 'GEC-B App mobile workflow' },
        ],
    },
    {
        id: 3,
        title: 'Structify',
        mark: 'ST',
        category: 'Interactive DSA platform',
        year: '2025',
        repoState: 'Public repo',
        repoUrl: 'https://github.com/Prahlad-07/Structify.io-',
        repoLabel: 'View Repository',
        summary: 'Learn data structures visually — watch the algorithms run.',
        description: 'Spring Boot backend, React frontend.',
        impact: [
            'Real-time algorithm visualizations',
            'JWT auth, role-based access',
            'Dockerized deployment',
        ],
        availabilityNote: 'Full-stack learning platform.',
        theme: { primary: '#1d4ed8', secondary: '#7c3aed' },
        tags: [
            { id: 1, name: 'Java', path: '/assets/file-java-color-green-icon.svg' },
            { id: 2, name: 'Spring Boot', path: '/assets/icons8-spring-boot.svg' },
            { id: 3, name: 'React', path: '/assets/react.svg' },
            { id: 4, name: 'MySQL', path: '/assets/mysql-icon.svg' },
            { id: 5, name: 'Docker' },
            { id: 6, name: 'JWT' },
        ],
        images: [
            { id: 1, src: '/assets/Projects-Images/Structify/firstImage.webp', alt: 'Structify home screen' },
            { id: 2, src: '/assets/Projects-Images/Structify/image%20copy.webp', alt: 'Structify learning interface' },
            { id: 3, src: '/assets/Projects-Images/Structify/image%20copy%202.webp', alt: 'Structify visualization screen' },
            { id: 4, src: '/assets/Projects-Images/Structify/image%20copy%203.webp', alt: 'Structify dashboard' },
        ],
    },
    {
        id: 4,
        title: 'CodeSiksha',
        mark: 'CS',
        category: 'Cross-platform DSA app',
        year: '2025',
        repoState: 'Public repo',
        repoUrl: 'https://github.com/Prahlad-07/CodeSiksha',
        repoLabel: 'View Repository',
        summary: 'Daily DSA practice — reminders, streaks, progress tracking.',
        description: 'Flutter, iOS and Android.',
        impact: [
            'Daily problems and streak tracking',
            'Firebase sync across devices',
            'Clean BLoC architecture',
        ],
        availabilityNote: 'Real mobile product, used by students.',
        theme: { primary: '#0f766e', secondary: '#1d4ed8' },
        tags: [
            { id: 1, name: 'Flutter' },
            { id: 2, name: 'Dart' },
            { id: 3, name: 'Firebase' },
            { id: 4, name: 'BLoC' },
            { id: 5, name: 'SQLite' },
        ],
        images: [
            { id: 1, src: '/assets/Projects-Images/CodeSiksha/1.webp', alt: 'CodeSiksha home screen' },
            { id: 2, src: '/assets/Projects-Images/CodeSiksha/2.webp', alt: 'CodeSiksha practice screen' },
            { id: 3, src: '/assets/Projects-Images/CodeSiksha/3.webp', alt: 'CodeSiksha dashboard' },
        ],
    },
    {
        id: 5,
        title: 'Bg-Removal AI SaaS',
        mark: 'BG',
        category: 'AI-powered SaaS product',
        year: '2025',
        repoState: 'Repository on request',
        repoUrl: '',
        repoLabel: 'Repository on Request',
        summary: 'Upload a photo, background removed. Credit-based payments.',
        description: 'Spring Boot APIs around an AI integration.',
        impact: [
            'Stripe + Razorpay credit payments',
            'Clean APIs around the AI integration',
            'Built to learn SaaS monetization',
        ],
        availabilityNote: 'Real product, real payments.',
        theme: { primary: '#7c3aed', secondary: '#1d4ed8' },
        tags: [
            { id: 1, name: 'Java', path: '/assets/file-java-color-green-icon.svg' },
            { id: 2, name: 'Spring Boot', path: '/assets/icons8-spring-boot.svg' },
            { id: 3, name: 'React', path: '/assets/react.svg' },
            { id: 4, name: 'MySQL', path: '/assets/mysql-icon.svg' },
            { id: 5, name: 'Razorpay' },
            { id: 6, name: 'Clerk' },
        ],
        images: [
            { id: 1, src: '/assets/Projects-Images/BG-Removal/img1.webp', alt: 'Background removal SaaS dashboard' },
            { id: 2, src: '/assets/Projects-Images/BG-Removal/img2.webp', alt: 'Background removal upload workflow' },
            { id: 3, src: '/assets/Projects-Images/BG-Removal/img3.webp', alt: 'Background removal credits interface' },
            { id: 4, src: '/assets/Projects-Images/BG-Removal/img4.webp', alt: 'Background removal account screen' },
        ],
    },
    {
        id: 6,
        title: 'Netflix Clone',
        mark: 'NF',
        category: 'Streaming UI clone',
        year: '2025',
        repoState: 'Public repo',
        repoUrl: 'https://github.com/Prahlad-07/Netflix-Clone',
        repoLabel: 'View Repository',
        summary: 'Netflix UI clone — built to learn React architecture.',
        description: 'React, Firebase, TMDB API.',
        impact: [
            'Browsing, trailers, working video player',
            'Firebase auth, protected routes',
            'TMDB API integration',
        ],
        availabilityNote: 'Learning project that taught me React.',
        theme: { primary: '#b91c1c', secondary: '#111827' },
        tags: [
            { id: 1, name: 'React', path: '/assets/react.svg' },
            { id: 2, name: 'JavaScript', path: '/assets/javascript-programming-language-icon.svg' },
            { id: 3, name: 'Firebase' },
            { id: 4, name: 'TMDB API' },
            { id: 5, name: 'CSS' },
        ],
        images: [
            { id: 1, src: '/assets/Projects-Images/Netflix-Clone/1.webp', alt: 'Netflix Clone homepage' },
            { id: 2, src: '/assets/Projects-Images/Netflix-Clone/2.webp', alt: 'Netflix Clone browsing interface' },
            { id: 3, src: '/assets/Projects-Images/Netflix-Clone/3.webp', alt: 'Netflix Clone player screen' },
            { id: 4, src: '/assets/Projects-Images/Netflix-Clone/4.webp', alt: 'Netflix Clone authentication screen' },
        ],
    },
];

export const workExperiences = [
    {
        id: 1,
        name: 'Newton School',
        pos: 'Software Development Engineer I',
        duration: 'Jun 2026 — Present',
        summary: 'Building and scaling the backend that powers the learning platform.',
        highlights: [
            'Designed a Redis-backed caching layer for high-traffic assignment data, cutting database load by ~70% and holding API response times under 50 ms for thousands of daily users.',
            'Built and shipped Dockerized REST APIs for assignment, user, and content-management services, secured end-to-end with Spring Cloud Gateway routing and JWT authentication.',
            'Hardened downstream service calls with Resilience4j circuit breakers and retry policies, keeping the platform responsive even when dependent services failed.',
        ],
        icon: '/assets/Newton-School.png',
        animation: 'victory',
    },
    {
        id: 2,
        name: 'Newton School',
        pos: 'Software Development Engineer Intern',
        duration: 'Dec 2025 — May 2026',
        summary: 'Backend services trusted by 10,000+ daily active users.',
        highlights: [
            'Maintained and scaled core backend services powering 10,000+ daily active users across Newton School and Newton School of Technology.',
            'Shipped a code-plagiarism detection system for the Athena assessment platform by integrating the industry-standard JPlag engine, giving instructors automated similarity reports.',
            'Owned bug fixes and feature slices end to end — from ticket to production — with test coverage and code review on every change.',
        ],
        icon: '/assets/Newton-School.png',
        animation: 'clapping',
    },
    {
        id: 3,
        name: 'MIDAS Lab',
        pos: 'Software Development Engineer Intern',
        duration: 'Jul 2024 — Sep 2024',
        summary: 'Delivered scalable feature modules for a production mobile app.',
        highlights: [
            'Integrated and validated RESTful APIs between the Android and backend teams, ensuring consistent data flow across services for a production app.',
            'Debugged production issues and drove fixes through code reviews and Agile sprint cycles, measurably improving module reliability and maintainability.',
            'Collaborated across Android and backend teams to design and ship feature modules on schedule.',
        ],
        icon: '/assets/MIDAS.png',
        animation: 'clapping',
    },
    {
        id: 4,
        name: 'TechCurators',
        pos: 'Problem Setter Intern',
        duration: 'May 2024 — Jul 2024',
        summary: 'Authored DSA problems used to screen engineering candidates.',
        highlights: [
            'Designed medium-to-hard DSA problems for technical hiring assessments, each with precise constraints, scoring rubrics, and reference solutions.',
            'Stress-tested every problem across edge and corner cases to guarantee correctness and a single optimal solution before release.',
        ],
        icon: '/assets/techcurators.png',
        animation: 'salute',
    },
];

export const clientReviews = [
    {
        id: 1,
        name: 'Satyendra Yadav',
        position: 'Principal Technical Program Manager, Perforce Software | Ex: Samsung R&D',
        img: '/assets/review2.webp',
        review:
            'Prahlad stands out for his ability to move from concept to reliable implementation quickly. He combines strong DSA depth with practical backend engineering, and his execution style is disciplined enough for production-oriented teams.',
    },
    {
        id: 2,
        name: 'Dr. Rajiv Ratn Shah',
        position: 'Founder, MIDAS',
        img: '/assets/review3.webp',
        review:
            'During his internship at MIDAS Lab, Prahlad worked closely with Android and backend teams and consistently delivered with ownership. His approach to API validation, debugging, and sprint collaboration reflected maturity beyond his experience level.',
    },
    {
        id: 3,
        name: 'Brijesh Shukla',
        position: 'Senior Electronic Engineer, Wabtec (United Kingdom)',
        img: '/assets/review4.webp',
        review:
            'Prahlad is focused, technically curious, and dependable. He learns fast, asks the right engineering questions, and then turns that clarity into measurable output. His consistency and work ethic make him a strong long-term contributor.',
    },
    {
        id: 4,
        name: 'Satyendra Yadav',
        position: 'Integration Lead, IBM | Ex: Accenture United Kingdom',
        img: '/assets/review1.webp',
        review:
            'I appreciate Prahlad\'s integration mindset. He understands how APIs, services, and system behavior connect end-to-end, and he communicates clearly while debugging issues under tight timelines. That combination is valuable in real delivery environments.',
    },
    {
        id: 5,
        name: 'Bhavya Garg',
        position: 'SDE, Newton School | Mentor of Prahlad',
        img: '/assets/review5.webp',
        review:
            'As Prahlad\'s mentor, I\'ve seen him stay punctual, accountable, and highly coachable. He keeps team energy positive with his humor, but when it comes to delivery, he is serious and reliable. He has grown into a strong, execution-first engineer.',
    },
];
